---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/totomk/public_html/mamaljubinkafinances.toto.mk/
    - if command -v rsync >/dev/null 2>&1; then RSYNC=$(command -v rsync); else RSYNC=/usr/bin/rsync; fi
    - $RSYNC -av --delete \
        --exclude ".git" \
        --exclude ".github" \
        --exclude ".cpanel" \
        --exclude ".well-known/" \
        ./ $DEPLOYPATH
